server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://containers-us-west-162.railway.app:7815/railway
    username: root
    password: 23WmFyzRNyApt11HpZPF
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  application:
    name: BOOK-STORE
  liquibase:
    contexts:
allowed-origins: https://book-store-ui-app.web.app
#springdoc:
#  api-docs:
#    path: /api/api-doc
#  swagger-ui:
#    path: /api/swagger-ui
