server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book-store
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  application:
    name: BOOK-STORE
  liquibase:
    contexts:
allowed-origins: http://localhost:4200
#springdoc:
#  api-docs:
#    path: /api/api-doc
#  swagger-ui:
#    path: /api/swagger-ui
